"use client";

import { useMemo, useState } from "react";
import { Button, Card, Status } from "../../packages/design-system";
import { hasPermission, type ModuleAccessContext } from "../../modules";

const sections = [
  ["Painel", "grid"], ["Contas a pagar", "payable"], ["Contas a receber", "receivable"],
  ["Fluxo de caixa", "chart"], ["Bancos e conciliação", "bank"], ["Centros de custo", "cost"],
  ["Relatórios", "report"], ["Homologação", "check"],
] as const;
type FinanceSection = (typeof sections)[number][0];
type PayableStatus = "Pendente" | "Em aprovação" | "Aprovado" | "Pago" | "Vencido";
type ReceivableStatus = "Em aberto" | "Recebido" | "Vencido" | "Parcial";
type Payable = { id:number; supplier:string; document:string; category:string; costCenter:string; due:string; value:number; status:PayableStatus };
type Receivable = { id:number; customer:string; document:string; category:string; due:string; value:number; received:number; status:ReceivableStatus };

const initialPayables:Payable[]=[
  {id:1,supplier:"Aços Boituva Ltda.",document:"NF 18452",category:"Matéria-prima",costCenter:"Produção",due:"2026-07-18",value:48290,status:"Em aprovação"},
  {id:2,supplier:"Energia Sul",document:"FAT 07/2026",category:"Energia elétrica",costCenter:"Industrial",due:"2026-07-19",value:27640,status:"Aprovado"},
  {id:3,supplier:"TechMold Serviços",document:"NF 0921",category:"Manutenção",costCenter:"Manutenção",due:"2026-07-15",value:12800,status:"Vencido"},
  {id:4,supplier:"Transportes Rápido SP",document:"CT-e 77108",category:"Fretes",costCenter:"Logística",due:"2026-07-25",value:7450,status:"Pendente"},
  {id:5,supplier:"Office Mais",document:"NF 5528",category:"Material administrativo",costCenter:"Administrativo",due:"2026-07-12",value:2380,status:"Pago"},
];
const initialReceivables:Receivable[]=[
  {id:1,customer:"Vidros Nacional S.A.",document:"NF-e 30218",category:"Venda de moldes",due:"2026-07-18",value:126500,received:0,status:"Em aberto"},
  {id:2,customer:"Cristal Forte",document:"NF-e 30204",category:"Venda de moldes",due:"2026-07-14",value:68400,received:0,status:"Vencido"},
  {id:3,customer:"Glass Brasil",document:"NF-e 30188",category:"Serviços técnicos",due:"2026-07-22",value:45200,received:20000,status:"Parcial"},
  {id:4,customer:"Embalagens Luz",document:"NF-e 30161",category:"Venda de moldes",due:"2026-07-09",value:93750,received:93750,status:"Recebido"},
];
const money=(value:number)=>value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const date=(value:string)=>new Date(`${value}T12:00:00`).toLocaleDateString("pt-BR");
const tone=(status:string):"success"|"attention"|"danger"|"info"|"neutral"=>status==="Pago"||status==="Recebido"?"success":status==="Vencido"?"danger":status.includes("aprovação")||status==="Parcial"?"attention":status==="Aprovado"?"info":"neutral";

function FIcon({name}:{name:string}){const paths:Record<string,React.ReactNode>={grid:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,payable:<><path d="M4 5h16v14H4zM7 9h10M7 13h6"/><path d="m16 16 2 2 3-4"/></>,receivable:<><path d="M4 5h16v14H4zM7 9h10M7 13h6"/><path d="M18 12v6M15 15h6"/></>,chart:<><path d="M4 20V10h4v10M10 20V4h4v16M16 20v-7h4v7"/></>,bank:<><path d="m3 9 9-6 9 6M5 10v8M9 10v8M15 10v8M19 10v8M3 21h18"/></>,cost:<><circle cx="12" cy="12" r="9"/><path d="M12 6v12M16 9c-1-2-7-2-7 1 0 3 7 1 7 5 0 3-6 3-8 1"/></>,report:<><path d="M6 3h9l4 4v14H6zM15 3v5h4M9 12h6M9 16h6"/></>,check:<><circle cx="12" cy="12" r="9"/><path d="m8 12 2.5 2.5L16 9"/></>,back:<path d="m15 18-6-6 6-6"/>,plus:<path d="M12 5v14M5 12h14"/>,arrow:<path d="m9 18 6-6-6-6"/>,close:<path d="m6 6 12 12M18 6 6 18"/>,search:<><circle cx="11" cy="11" r="7"/><path d="m16 16 5 5"/></>,alert:<><path d="M12 3 2 21h20L12 3Z"/><path d="M12 9v5M12 18h.01"/></>};return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden>{paths[name]}</svg>}

export function FinanceModule({notify,onEvent,onExit,access}:{notify:(message:string)=>void;onEvent:(message:string,module?:string)=>void;onExit:()=>void;access:ModuleAccessContext}){
  const [section,setSection]=useState<FinanceSection>("Painel");
  const [payables,setPayables]=useState(initialPayables);
  const [receivables,setReceivables]=useState(initialReceivables);
  const [modal,setModal]=useState<"payable"|"receivable"|"report"|null>(null);
  const [selected,setSelected]=useState<Payable|Receivable|null>(null);
  const [homologation,setHomologation]=useState([true,true,true,true,false,false]);
  const track=(message:string)=>{notify(message);onEvent(message,"Financeiro")};
  const canCreate=hasPermission(access,"financeiro.create");
  const canApprove=hasPermission(access,"financeiro.approve");
  const canSettle=hasPermission(access,"financeiro.settle");
  const canReconcile=hasPermission(access,"financeiro.reconcile");
  const canExport=hasPermission(access,"financeiro.export");
  const canAdmin=hasPermission(access,"financeiro.admin");
  const accessibleSections=canAdmin?sections:sections.filter(([label])=>label!=="Homologação");
  const render=()=>section==="Painel"?<Dashboard payables={payables} receivables={receivables} setSection={setSection} access={access}/>:section==="Contas a pagar"?<Payables data={payables} setData={setPayables} canCreate={canCreate} canApprove={canApprove} canSettle={canSettle} openCreate={()=>setModal("payable")} inspect={setSelected} track={track}/>:section==="Contas a receber"?<Receivables data={receivables} setData={setReceivables} canCreate={canCreate} canSettle={canSettle} openCreate={()=>setModal("receivable")} inspect={setSelected} track={track}/>:section==="Fluxo de caixa"?<CashFlow payables={payables} receivables={receivables}/>:section==="Bancos e conciliação"?<Banks track={track} canReconcile={canReconcile}/>:section==="Centros de custo"?<CostCenters track={track} canCreate={canCreate}/>:section==="Relatórios"?<Reports open={(title)=>{setSelected({id:0,customer:title,document:"",category:"",due:"",value:0,received:0,status:"Em aberto"});setModal("report")}}/>:<Homologation values={homologation} setValues={setHomologation} track={track}/>;
  return <div className="finance-module"><div className="finance-module-bar"><button onClick={onExit}><FIcon name="back"/> Ecossistema</button><span><FIcon name="chart"/><b>Financeiro</b><small>Módulo Financeiro</small></span><Status tone="success">Integrado à Fundação</Status></div><div className="finance-layout"><aside className="finance-navigation"><p>GESTÃO FINANCEIRA</p>{accessibleSections.map(([label,icon])=><button key={label} className={section===label?"active":""} onClick={()=>setSection(label)}><FIcon name={icon}/><span>{label}</span>{label==="Contas a pagar"&&<i>{payables.filter(x=>x.status==="Vencido").length}</i>}</button>)}<div className="finance-scope"><FIcon name="check"/><span><b>Escopo atual</b><small>{access.scopeLabel}</small></span></div></aside><main className="finance-workspace">{render()}</main></div>{modal==="payable"&&<EntryForm kind="payable" onClose={()=>setModal(null)} onSave={(entry)=>{setPayables(current=>[{id:Date.now(),...(entry as Omit<Payable,"id">)},...current]);setModal(null);track("Conta a pagar cadastrada.")}}/>}{modal==="receivable"&&<EntryForm kind="receivable" onClose={()=>setModal(null)} onSave={(entry)=>{setReceivables(current=>[{id:Date.now(),...(entry as Omit<Receivable,"id">)},...current]);setModal(null);track("Conta a receber cadastrada.")}}/>}{selected&&modal!=="report"&&<Detail item={selected} onClose={()=>setSelected(null)}/>} {modal==="report"&&<ReportDetail title={(selected as Receivable)?.customer??"Relatório financeiro"} canExport={canExport} track={track} onClose={()=>{setModal(null);setSelected(null)}}/>}</div>
}

function Header({eyebrow,title,description,action,onAction}:{eyebrow:string;title:string;description:string;action?:string;onAction?:()=>void}){return <div className="finance-page-head"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div>{action&&<Button onClick={onAction}><FIcon name="plus"/> {action}</Button>}</div>}
function Metric({value,label,meta,toneName,icon}:{value:string;label:string;meta:string;toneName:string;icon:string}){return <Card className={`finance-stat ${toneName}`}><span><FIcon name={icon}/></span><div><strong>{value}</strong><b>{label}</b><small>{meta}</small></div></Card>}
function Dashboard({payables,receivables,setSection,access}:{payables:Payable[];receivables:Receivable[];setSection:(v:FinanceSection)=>void;access:ModuleAccessContext}){const payableOpen=payables.filter(x=>x.status!=="Pago").reduce((a,b)=>a+b.value,0);const receiveOpen=receivables.reduce((a,b)=>a+b.value-b.received,0);return <><Header eyebrow={`FINANCEIRO · ${access.role.toUpperCase()}`} title="Visão financeira" description={`Caixa, compromissos e recebíveis autorizados para ${access.scopeLabel.toLowerCase()}.`}/><div className="finance-stats"><Metric value={money(842350)} label="Saldo disponível" meta="4 contas bancárias" toneName="blue" icon="bank"/><Metric value={money(receiveOpen)} label="A receber" meta="Próximos 30 dias" toneName="green" icon="receivable"/><Metric value={money(payableOpen)} label="A pagar" meta="Próximos 30 dias" toneName="orange" icon="payable"/><Metric value={money(126840)} label="Caixa projetado" meta="Fechamento do mês" toneName="purple" icon="chart"/></div><div className="finance-dashboard-grid"><Card className="finance-pending"><div className="finance-card-head"><div><p className="eyebrow">CENTRAL FINANCEIRA</p><h2>Ações que exigem atenção</h2><p>Compromissos, cobranças e conciliações pendentes.</p></div><Status tone="attention">5 pendências</Status></div>{[["Pagamento vencido · TechMold","R$ 12.800 · venceu em 15 jul","Contas a pagar"],["Título vencido · Cristal Forte","R$ 68.400 · cobrança pendente","Contas a receber"],["Conciliação bancária","3 lançamentos sem correspondência","Bancos e conciliação"]].map(([title,meta,target],i)=><button key={title} onClick={()=>setSection(target as FinanceSection)}><span><FIcon name={i===0?"payable":i===1?"receivable":"bank"}/></span><span><b>{title}</b><small>{meta}</small></span><Status tone={i<2?"danger":"attention"}>{i<2?"Prioridade":"Conferir"}</Status><FIcon name="arrow"/></button>)}</Card><Card className="finance-position"><p className="eyebrow">POSIÇÃO DO MÊS</p><h2>Entradas e saídas</h2><div className="finance-donut"><span><b>R$ 126,8 mil</b><small>Saldo projetado</small></span></div><dl><div><dt>Receitas previstas</dt><dd>R$ 842.400</dd></div><div><dt>Despesas previstas</dt><dd>R$ 715.560</dd></div><div><dt>Margem de caixa</dt><dd>15,1%</dd></div></dl><button onClick={()=>setSection("Fluxo de caixa")}>Ver fluxo completo <FIcon name="arrow"/></button></Card></div></>}

function Payables({data,setData,canCreate,canApprove,canSettle,openCreate,inspect,track}:{data:Payable[];setData:React.Dispatch<React.SetStateAction<Payable[]>>;canCreate:boolean;canApprove:boolean;canSettle:boolean;openCreate:()=>void;inspect:(x:Payable)=>void;track:(m:string)=>void}){const[query,setQuery]=useState("");const[filter,setFilter]=useState("Todos");const visible=useMemo(()=>data.filter(x=>(filter==="Todos"||x.status===filter)&&`${x.supplier} ${x.document} ${x.category}`.toLowerCase().includes(query.toLowerCase())),[data,query,filter]);const update=(id:number,status:PayableStatus)=>{setData(current=>current.map(x=>x.id===id?{...x,status}:x));track(`Conta a pagar: situação alterada para ${status}.`)};return <><Header eyebrow="FINANCEIRO · OBRIGAÇÕES" title="Contas a pagar" description="Títulos, vencimentos, aprovações e pagamentos por centro de custo." action={canCreate?"Nova conta":undefined} onAction={openCreate}/><div className="finance-toolbar"><label><FIcon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar fornecedor, documento ou categoria..."/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option>Todos</option><option>Pendente</option><option>Em aprovação</option><option>Aprovado</option><option>Pago</option><option>Vencido</option></select></div><Card className="finance-table-card"><div className="finance-table payable"><div className="head"><span>Fornecedor</span><span>Vencimento</span><span>Centro de custo</span><span>Valor</span><span>Situação</span><span/></div>{visible.map(x=><div className="row" key={x.id}><button className="title" onClick={()=>inspect(x)}><b>{x.supplier}</b><small>{x.document} · {x.category}</small></button><span>{date(x.due)}</span><span>{x.costCenter}</span><strong>{money(x.value)}</strong><Status tone={tone(x.status)}>{x.status}</Status><span className="actions">{canApprove&&(x.status==="Pendente"||x.status==="Em aprovação")&&<button onClick={()=>update(x.id,"Aprovado")}>Aprovar</button>}{canSettle&&x.status==="Aprovado"&&<button onClick={()=>update(x.id,"Pago")}>Pagar</button>}<button onClick={()=>inspect(x)} aria-label={`Detalhes de ${x.supplier}`}><FIcon name="arrow"/></button></span></div>)}</div></Card></>}

function Receivables({data,setData,canCreate,canSettle,openCreate,inspect,track}:{data:Receivable[];setData:React.Dispatch<React.SetStateAction<Receivable[]>>;canCreate:boolean;canSettle:boolean;openCreate:()=>void;inspect:(x:Receivable)=>void;track:(m:string)=>void}){const[query,setQuery]=useState("");const visible=data.filter(x=>`${x.customer} ${x.document}`.toLowerCase().includes(query.toLowerCase()));const receive=(id:number)=>{setData(current=>current.map(x=>x.id===id?{...x,received:x.value,status:"Recebido"}:x));track("Conta a receber: recebimento confirmado.")};return <><Header eyebrow="FINANCEIRO · RECEITAS" title="Contas a receber" description="Títulos, recebimentos, inadimplência e acompanhamento de cobrança." action={canCreate?"Novo recebível":undefined} onAction={openCreate}/><div className="finance-toolbar"><label><FIcon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente ou documento..."/></label><Status tone="danger">1 título vencido</Status></div><Card className="finance-table-card"><div className="finance-table receivable"><div className="head"><span>Cliente</span><span>Vencimento</span><span>Valor</span><span>Recebido</span><span>Situação</span><span/></div>{visible.map(x=><div className="row" key={x.id}><button className="title" onClick={()=>inspect(x)}><b>{x.customer}</b><small>{x.document} · {x.category}</small></button><span>{date(x.due)}</span><strong>{money(x.value)}</strong><span>{money(x.received)}</span><Status tone={tone(x.status)}>{x.status}</Status><span className="actions">{canSettle&&x.status!=="Recebido"&&<button onClick={()=>receive(x.id)}>Receber</button>}<button onClick={()=>inspect(x)} aria-label={`Detalhes de ${x.customer}`}><FIcon name="arrow"/></button></span></div>)}</div></Card></>}

function CashFlow({payables,receivables}:{payables:Payable[];receivables:Receivable[]}){const months=[{m:"JUL",in:842,out:716},{m:"AGO",in:910,out:768},{m:"SET",in:875,out:702},{m:"OUT",in:980,out:824},{m:"NOV",in:1040,out:861},{m:"DEZ",in:1120,out:945}];return <><Header eyebrow="FINANCEIRO · TESOURARIA" title="Fluxo de caixa" description="Visão realizada e projetada das disponibilidades financeiras."/><div className="finance-stats compact"><Metric value={money(receivables.reduce((a,b)=>a+b.received,0))} label="Entradas realizadas" meta="Julho de 2026" toneName="green" icon="receivable"/><Metric value={money(payables.filter(x=>x.status==="Pago").reduce((a,b)=>a+b.value,0))} label="Saídas realizadas" meta="Julho de 2026" toneName="orange" icon="payable"/><Metric value="R$ 126,8 mil" label="Resultado projetado" meta="Fechamento mensal" toneName="blue" icon="chart"/></div><Card className="cash-chart"><div className="finance-card-head"><div><p className="eyebrow">PROJEÇÃO DE 6 MESES</p><h2>Entradas versus saídas</h2><p>Valores demonstrativos em milhares de reais.</p></div><div className="legend"><span className="in">Entradas</span><span className="out">Saídas</span></div></div><div className="cash-bars">{months.map(x=><div key={x.m}><div><i className="in" style={{height:`${x.in/12}px`}}/><i className="out" style={{height:`${x.out/12}px`}}/></div><b>{x.m}</b><small>+{money((x.in-x.out)*1000).replace(",00","")}</small></div>)}</div></Card></>}

function Banks({track,canReconcile}:{track:(m:string)=>void;canReconcile:boolean}){const[items,setItems]=useState([["Banco do Brasil · 4521-7","Conta corrente","R$ 428.650","Conciliada"],["Itaú · 88304-2","Conta corrente","R$ 296.180","3 pendências"],["Santander · 10298-4","Conta pagamentos","R$ 117.520","Conciliada"],["Caixa · Aplicação","Reserva financeira","R$ 680.000","Atualizada"]]);const reconcile=(index:number)=>{setItems(current=>current.map((x,i)=>i===index?[x[0],x[1],x[2],"Conciliada"]:x));track("Conciliação bancária concluída.")};return <><Header eyebrow="FINANCEIRO · BANCOS" title="Bancos e conciliação" description="Saldos e correspondência demonstrativa entre extrato e lançamentos." action={canReconcile?"Importar extrato":undefined} onAction={()=>track("Extrato OFX demonstrativo importado.")}/><div className="bank-grid">{items.map((x,i)=><Card key={x[0]} className="bank-card"><span><FIcon name="bank"/></span><Status tone={x[3]==="Conciliada"||x[3]==="Atualizada"?"success":"attention"}>{x[3]}</Status><h2>{x[0]}</h2><p>{x[1]}</p><strong>{x[2]}</strong><small>Saldo demonstrativo disponível</small>{canReconcile&&x[3]!=="Conciliada"&&x[3]!=="Atualizada"?<Button onClick={()=>reconcile(i)}>Conciliar agora</Button>:<button onClick={()=>track(`${x[0]}: extrato aberto.`)}>Ver movimentações <FIcon name="arrow"/></button>}</Card>)}</div></>}

function CostCenters({track,canCreate}:{track:(m:string)=>void;canCreate:boolean}){const centers=[["Produção","R$ 382.400","53%","Industrial"],["Manutenção","R$ 96.850","14%","Industrial"],["Administrativo","R$ 82.300","11%","Corporativo"],["Comercial","R$ 71.600","10%","Corporativo"],["Qualidade","R$ 54.200","8%","Industrial"],["RH e SST","R$ 28.210","4%","Corporativo"]];return <><Header eyebrow="FINANCEIRO · CLASSIFICAÇÃO" title="Centros de custo" description="Distribuição gerencial das despesas e orçamento por área." action={canCreate?"Novo centro":undefined} onAction={()=>track("Cadastro demonstrativo de centro de custo iniciado.")}/><div className="cost-grid">{centers.map(([name,value,share,group])=><Card key={name}><span><FIcon name="cost"/></span><Status>{group}</Status><h2>{name}</h2><strong>{value}</strong><small>Realizado no mês · {share} do total</small><div><i style={{width:share}}/></div><button onClick={()=>track(`${name}: lançamentos do centro de custo abertos.`)}>Ver lançamentos <FIcon name="arrow"/></button></Card>)}</div></>}

function Reports({open}:{open:(title:string)=>void}){const reports=[["Posição financeira","Saldos, compromissos e disponibilidades atuais."],["Contas a pagar por vencimento","Agenda financeira e exposição por fornecedor."],["Contas a receber e inadimplência","Recebíveis, atrasos e recuperação de crédito."],["Fluxo de caixa projetado","Entradas e saídas previstas para 12 meses."],["Despesas por centro de custo","Realizado, orçamento e variações por área."],["Conciliação bancária","Correspondências e pendências por conta."]];return <><Header eyebrow="FINANCEIRO · INTELIGÊNCIA" title="Relatórios financeiros" description="Indicadores preparados para a inteligência corporativa do Pecsil Business OS."/><div className="finance-report-grid">{reports.map(([title,desc],i)=><Card key={title}><span><FIcon name="report"/></span><Status tone={i===2||i===5?"attention":"success"}>{i===2||i===5?"Atenção":"Atualizado"}</Status><h2>{title}</h2><p>{desc}</p><button onClick={()=>open(title)}>Abrir relatório <FIcon name="arrow"/></button></Card>)}</div></>}

function Homologation({values,setValues,track}:{values:boolean[];setValues:React.Dispatch<React.SetStateAction<boolean[]>>;track:(m:string)=>void}){const checks=[["Contrato do módulo","Manifesto, rota e permissões registrados"],["Contas a pagar","Cadastro, aprovação e liquidação validados"],["Contas a receber","Cadastro, recebimento e cobrança validados"],["Fluxo e bancos","Projeção e conciliação demonstrativas"],["Matriz de acessos","Validação final com diretoria e financeiro"],["Persistência real","Supabase, RLS e auditoria permanente"]];const done=values.filter(Boolean).length;return <><Header eyebrow="FINANCEIRO · GOVERNANÇA" title="Homologação do módulo" description="Critérios funcionais e técnicos para liberar o Financeiro em produção."/><div className="homologation-layout"><Card className="homologation-progress"><p className="eyebrow">PROGRESSO ATUAL</p><strong>{Math.round(done/checks.length*100)}%</strong><div><i style={{width:`${done/checks.length*100}%`}}/></div><h2>{done===checks.length?"Módulo homologado":"Validação em andamento"}</h2><p>{checks.length-done} critérios ainda precisam de confirmação.</p>{done===checks.length&&<Button onClick={()=>track("Módulo Financeiro homologado para produção.")}>Homologar módulo</Button>}</Card><Card className="homologation-checks">{checks.map(([title,meta],i)=><button key={title} onClick={()=>setValues(current=>current.map((v,n)=>n===i?!v:v))}><span className={values[i]?"done":""}>{values[i]?"✓":i+1}</span><span><b>{title}</b><small>{meta}</small></span><Status tone={values[i]?"success":"neutral"}>{values[i]?"Validado":"Pendente"}</Status></button>)}</Card></div></>}

function EntryForm({kind,onClose,onSave}:{kind:"payable"|"receivable";onClose:()=>void;onSave:(entry:Omit<Payable,"id">|Omit<Receivable,"id">)=>void}){const[party,setParty]=useState("");const[document,setDocument]=useState("");const[value,setValue]=useState("");const[due,setDue]=useState("2026-07-31");const[category,setCategory]=useState("");const[costCenter,setCostCenter]=useState("Administrativo");const submit=(e:React.FormEvent)=>{e.preventDefault();const numeric=Number(value.replace(/[^0-9,]/g,"").replace(",","."));if(!party||!document||!numeric)return;if(kind==="payable")onSave({supplier:party,document,category:category||"Outras despesas",costCenter,due,value:numeric,status:"Pendente"});else onSave({customer:party,document,category:category||"Outras receitas",due,value:numeric,received:0,status:"Em aberto"})};return <div className="finance-layer" onMouseDown={onClose}><form onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><div><p className="eyebrow">FINANCEIRO · NOVO LANÇAMENTO</p><h2>{kind==="payable"?"Nova conta a pagar":"Nova conta a receber"}</h2><p>Registre um título demonstrativo para o fluxo financeiro.</p></div><button type="button" onClick={onClose}><FIcon name="close"/></button></header><div className="finance-form-fields"><label><span>{kind==="payable"?"Fornecedor":"Cliente"} *</span><input value={party} onChange={e=>setParty(e.target.value)}/></label><label><span>Documento *</span><input value={document} onChange={e=>setDocument(e.target.value)} placeholder="Ex.: NF 12345"/></label><label><span>Categoria</span><input value={category} onChange={e=>setCategory(e.target.value)}/></label>{kind==="payable"&&<label><span>Centro de custo</span><select value={costCenter} onChange={e=>setCostCenter(e.target.value)}><option>Administrativo</option><option>Produção</option><option>Manutenção</option><option>Qualidade</option><option>Logística</option></select></label>}<label><span>Vencimento *</span><input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label><span>Valor *</span><input value={value} onChange={e=>setValue(e.target.value)} placeholder="0,00" inputMode="decimal"/></label></div><footer><button type="button" onClick={onClose}>Cancelar</button><Button type="submit">Salvar lançamento</Button></footer></form></div>}
function Detail({item,onClose}:{item:Payable|Receivable;onClose:()=>void}){const isPayable="supplier" in item;return <div className="finance-layer" onMouseDown={onClose}><Card className="finance-detail" onMouseDown={e=>e.stopPropagation()}><header><div><p className="eyebrow">DETALHE DO TÍTULO</p><h2>{isPayable?item.supplier:item.customer}</h2><p>{item.document}</p></div><button onClick={onClose}><FIcon name="close"/></button></header><dl><div><dt>Natureza</dt><dd>{isPayable?"Conta a pagar":"Conta a receber"}</dd></div><div><dt>Categoria</dt><dd>{item.category}</dd></div><div><dt>Vencimento</dt><dd>{date(item.due)}</dd></div><div><dt>Valor</dt><dd>{money(item.value)}</dd></div><div><dt>Situação</dt><dd><Status tone={tone(item.status)}>{item.status}</Status></dd></div></dl><div className="finance-detail-note"><FIcon name="alert"/><span><b>Registro demonstrativo</b><small>Documentos, histórico e auditoria serão persistidos quando o Supabase estiver conectado.</small></span></div></Card></div>}
function ReportDetail({title,onClose,canExport,track}:{title:string;onClose:()=>void;canExport:boolean;track:(m:string)=>void}){return <div className="finance-layer" onMouseDown={onClose}><Card className="finance-detail report" onMouseDown={e=>e.stopPropagation()}><header><div><p className="eyebrow">RELATÓRIO FINANCEIRO</p><h2>{title}</h2><p>Posição consolidada · Julho de 2026</p></div><button onClick={onClose}><FIcon name="close"/></button></header><div className="report-summary"><span><small>Saldo atual</small><b>R$ 842.350</b></span><span><small>Resultado projetado</small><b>R$ 126.840</b></span><span><small>Variação mensal</small><b>+8,4%</b></span></div><div className="report-placeholder"><FIcon name="chart"/><b>Visualização consolidada preparada</b><small>Exportação e dados reais serão ativados na etapa de persistência.</small></div>{canExport&&<footer><Button onClick={()=>track(`${title}: exportação demonstrativa concluída.`)}>Exportar demonstrativo</Button></footer>}</Card></div>}
